// GENERATED FILE — 请勿手改。
// 由 scripts/tools/gen_settings_search_index.dart 从设置页源码生成。
// 重新生成：dart run scripts/tools/gen_settings_search_index.dart
// 注意：设置页已两层化（子页 ≤4 的分类内联进分类 body），
// 内联条目的 subpage 为空串；本文件已按两层化后的 UI 手动同步。

/// 设置搜索索引：label 取自各分类页 tile 的标题，category 为所属分类，
/// subpage 为所属三级子页（空串 = 二级页内联项），
/// aliases 来自源码中的 `// search: ...` 标注（补充同义词匹配）。
const List<({String label, String category, String subpage, String aliases})>
    kSettingsSearchIndex = [
  (label: 'OLED 纯黑深色', category: '外观', subpage: '主题与配色', aliases: 'oled 纯黑 深色 黑色'),
  (label: '使用系统主题色', category: '外观', subpage: '主题与配色', aliases: '系统主题 壁纸 莫奈'),
  (label: '封面动态取色', category: '外观', subpage: '主题与配色', aliases: '动态取色 封面'),
  (label: '主题色', category: '外观', subpage: '主题与配色', aliases: '主题 颜色 换肤'),
  (label: '主题与配色', category: '外观', subpage: '主题与配色', aliases: ''),
  (label: '底部导航栏', category: '外观', subpage: '', aliases: '标签 显示 隐藏 导航'),
  (label: '桌面布局', category: '外观', subpage: '', aliases: '桌面布局 侧栏 大屏 平板 横屏 双栏 工具栏 desktop'),
  (label: '车机模式', category: '外观', subpage: '车机模式', aliases: '车机 车载 常驻 面板 大屏 副屏 副驾 miniplayer 迷你条'),
  (label: '检测到车机屏幕时自动开启', category: '外观', subpage: '车机模式', aliases: '车机 车载 自动 检测 屏幕 分辨率 识别 竖屏 方屏'),
  (label: 'dock 避让高度', category: '外观', subpage: '车机模式', aliases: '车机 车联 dock 避让 底部 空隙 高度'),
  (label: '面板位置', category: '外观', subpage: '车机模式', aliases: '车机 面板 左侧 右侧 停靠 位置'),
  (label: '启用自定义背景图片', category: '外观', subpage: '界面背景', aliases: '背景 图片 壁纸'),
  (label: '选择背景图片', category: '外观', subpage: '界面背景', aliases: '背景 图片 选择 更换'),
  (label: '清除背景图片', category: '外观', subpage: '界面背景', aliases: '背景 图片 清除 移除'),
  (label: '背景图片模糊', category: '外观', subpage: '界面背景', aliases: '模糊 高斯模糊 背景'),
  (label: '背景图片透明度', category: '外观', subpage: '界面背景', aliases: '透明度 背景'),
  (label: '按背景图莫奈取色', category: '外观', subpage: '界面背景', aliases: '莫奈 取色 动态取色 背景'),
  (label: '文字阴影', category: '外观', subpage: '界面背景', aliases: '阴影 文字 可读性 背景 壁纸'),
  (label: '界面背景', category: '外观', subpage: '界面背景', aliases: ''),
  (label: '歌词双击跳转', category: '播放页样式', subpage: '封面与动态', aliases: '双击 跳转'),
  (label: '专辑动态封面', category: '播放页样式', subpage: '封面与动态', aliases: '动态封面 专辑封面 短视频 全屏播放器 封面动画'),
  (label: '移动网络下加载动态封面', category: '播放页样式', subpage: '封面与动态', aliases: '动态封面 移动网络 流量 蜂窝 wifi'),
  (label: '3D 封面', category: '播放页样式', subpage: '封面与动态', aliases: '3D 封面;深度;视差;立体;封面'),
  (label: '3D 封面强度', category: '播放页样式', subpage: '封面与动态', aliases: '3D 封面 强度;视差 灵敏度;陀螺仪 灵敏度;深度 幅度'),
  (label: 'AI 背景修补', category: '播放页样式', subpage: '封面与动态', aliases: '3D 封面 AI 修补;背景 修补;神经网络;模型 修补;智能 填充'),
  (label: '清理深度图缓存', category: '播放页样式', subpage: '封面与动态', aliases: '3D 封面 缓存;清理 缓存;深度 缓存'),
  (label: '封面与动态', category: '播放页样式', subpage: '封面与动态', aliases: ''),
  (label: '歌手写真背景轮播', category: '播放页样式', subpage: '', aliases: '写真 背景 轮播'),
  (label: '轮播间隔', category: '播放页样式', subpage: '', aliases: '写真 轮播 间隔'),
  (label: '写真背景透明度', category: '播放页样式', subpage: '', aliases: '写真 透明度'),
  (label: 'ColorOS Bridge 兼容字段', category: '歌词', subpage: '', aliases: ''),
  (label: '翻译歌词', category: '歌词', subpage: '', aliases: '翻译'),
  (label: '罗马音歌词', category: '歌词', subpage: '', aliases: '罗马音 拼音'),
  (label: '优先翻译（同时存在时）', category: '歌词', subpage: '', aliases: '优先 翻译'),
  (label: '歌词推送', category: '歌词', subpage: '', aliases: ''),
  (label: '蓝牙歌词', category: '歌词', subpage: '', aliases: '蓝牙'),
  (label: '压缩封面图', category: '歌词', subpage: '', aliases: '蓝牙 封面 压缩'),
  (label: '歌词同步', category: '歌词', subpage: '', aliases: '时间偏移 同步 偏移'),
  (label: '网络音质', category: '播放', subpage: '音质与输出', aliases: '音质 清晰度 wifi 移动'),
  (label: '自动领取VIP', category: '播放', subpage: '音质与输出', aliases: 'vip 会员 自动领取'),
  (label: '32bit 播放支持', category: '播放', subpage: '音质与输出', aliases: '32bit 无损 高解析 音质 float'),
  (label: '音质降级提示', category: '播放', subpage: '音质与输出', aliases: '音质 降级 提示 toast vip 网络限制'),
  (label: '音质与输出', category: '播放', subpage: '音质与输出', aliases: ''),
  (label: '均衡器', category: '播放', subpage: '音效与音量', aliases: 'eq 均衡'),
  (label: '禁用App均衡器和音效', category: '播放', subpage: '音效与音量', aliases: '禁用系统音效 手机厂商 音效叠加 爆音 均衡器'),
  (label: '音效库', category: '播放', subpage: '音效与音量', aliases: '蝰蛇 音效 社区音效 sound model irs'),
  (label: '蝰蛇母带处理', category: '播放', subpage: '音效与音量', aliases: '蝰蛇 母带 母带处理 限幅 削波 均衡 viper master'),
  (label: '蝰蛇母带音源', category: '播放', subpage: '音效与音量', aliases: '蝰蛇母带 音源 母带音质 viper tape VPT'),
  (label: '音量均衡', category: '播放', subpage: '音效与音量', aliases: '音量均衡 响度归一 响度 均衡 参考响度 LUFS 安静歌 放大 峰值'),
  (label: '参考响度 LUFS', category: '播放', subpage: '音效与音量', aliases: '音量均衡 参考响度 响度 归一 均衡'),
  (label: '参考响度', category: '播放', subpage: '音效与音量', aliases: ''),
  (label: '音效与音量', category: '播放', subpage: '音效与音量', aliases: ''),
  (label: '记忆播放状态', category: '播放', subpage: '播放行为', aliases: '记忆 播放状态 恢复 上次播放 播放进度 断点 续播 冷启动'),
  (label: '启动时自动播放', category: '播放', subpage: '播放行为', aliases: '自动播放 启动 开机 冷启动 一进来 就播'),
  (label: '播放内容', category: '播放', subpage: '播放行为', aliases: '播放内容 音源 每日推荐 继续上次 续播'),
  (label: '自动打开播放页', category: '播放', subpage: '播放行为', aliases: '自动打开 播放页 全屏 推起 进播放页 启动'),
  (label: '暂停淡入淡出', category: '播放', subpage: '播放行为', aliases: '淡入淡出 渐变 音量'),
  (label: '歌曲淡入淡出', category: '播放', subpage: '播放行为', aliases: '歌曲淡入淡出 交叉淡化 crossfade 渐入渐出 叠加 衔接 无缝 过渡'),
  (label: '淡出时长', category: '播放', subpage: '播放行为', aliases: '交叉淡化时长 淡化 时长 秒数 crossfade 叠加'),
  (label: '自动混音（AutoMix）', category: '播放', subpage: '播放行为', aliases: '自动混音 AutoMix 无缝过渡 对拍 节拍 变速 混音 DJ'),
  (label: '允许与其他应用同时播放音频', category: '播放', subpage: '播放行为', aliases: '音频焦点 忽略焦点 同时播放 共存 不被打断 焦点'),
  (label: '上传听歌时长', category: '播放', subpage: '播放行为', aliases: '上传听歌时长 听歌时长 上传 等级 累计 上报'),
  (label: '播放行为', category: '播放', subpage: '播放行为', aliases: ''),
  (label: '长按封面进入 Zen 模式', category: '播放', subpage: '', aliases: 'zen 沉浸 长按封面 沉浸模式'),
  (label: '横屏隐藏状态栏', category: '播放', subpage: '', aliases: '横屏 沉浸 状态栏 导航栏 隐藏 全屏播放器'),
  (label: '播放时保持屏幕常亮', category: '播放', subpage: '', aliases: '屏幕常亮 常亮 息屏'),
  (label: '关闭本地音乐评论区', category: '播放', subpage: '', aliases: '本地音乐 评论区 评论 tab 看评论 关闭评论 本地歌曲'),
  (label: '收藏歌单按最近点击排序', category: '播放', subpage: '', aliases: '收藏 歌单 排序 最近点击 顺序'),
  (label: '主页 Tab 管理', category: '主页管理', subpage: '', aliases: 'tab 标签页 主页'),
  (label: '桌面快捷方式', category: '桌面快捷方式', subpage: '', aliases: '快捷方式 快捷 长按'),
  (label: '本地数据接口', category: '缓存与数据', subpage: '', aliases: '接口 本地服务器 api 在线音乐'),
  (label: '清除缓存', category: '缓存与数据', subpage: '', aliases: '缓存 清除'),
  (label: '数据迁移（修复数据混乱）', category: '缓存与数据', subpage: '', aliases: '迁移 数据 修复'),
  (label: '应用版本', category: '关于', subpage: '', aliases: '版本 检查更新'),
  (label: '新版本提醒', category: '关于', subpage: '', aliases: '更新 新版本 升级 upgrade 提醒'),
  (label: '还原旧版本 App 图标', category: '关于', subpage: '', aliases: '图标 旧版 桌面图标 恢复'),
  (label: '更新最新版本', category: '关于', subpage: '', aliases: '更新'),
  (label: '当前渲染引擎', category: '关于', subpage: '', aliases: '渲染引擎 渲染 引擎 图形 兼容 skia impeller 构建'),
  (label: '新手教程', category: '关于', subpage: '', aliases: '教程 引导'),
  (label: '导出诊断日志', category: '关于', subpage: '', aliases: '日志 诊断 导出 反馈 bug log'),
  (label: '清空诊断日志', category: '关于', subpage: '', aliases: '清空日志 删除日志'),
  (label: '用户协议', category: '关于', subpage: '', aliases: '协议 条款'),
  (label: '免责声明', category: '关于', subpage: '', aliases: '免责'),
  (label: '开源许可', category: '关于', subpage: '', aliases: '开源 license 许可'),
];
